//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\bilsa\AppData\Roaming\RapidEditor\Extensions\Rapid_Extensions_Antlr\code_gen\201801\14\04\22\33_956\JSON.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJSONListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class JSONBaseListener : IJSONListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] JSONParser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] JSONParser.JsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.topDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopDeclarations([NotNull] JSONParser.TopDeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.topDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopDeclarations([NotNull] JSONParser.TopDeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.topDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopDeclaration([NotNull] JSONParser.TopDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.topDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopDeclaration([NotNull] JSONParser.TopDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleDeclaration([NotNull] JSONParser.RuleDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleDeclaration([NotNull] JSONParser.RuleDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleDef([NotNull] JSONParser.RuleDefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleDef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleDef([NotNull] JSONParser.RuleDefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleExpressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleExpressions([NotNull] JSONParser.RuleExpressionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleExpressions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleExpressions([NotNull] JSONParser.RuleExpressionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRuleExpr([NotNull] JSONParser.RuleExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRuleExpr([NotNull] JSONParser.RuleExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.regexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegexExpr([NotNull] JSONParser.RegexExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.regexExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegexExpr([NotNull] JSONParser.RegexExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.refExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefExpr([NotNull] JSONParser.RefExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.refExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefExpr([NotNull] JSONParser.RefExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.spellingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpellingExpr([NotNull] JSONParser.SpellingExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.spellingExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpellingExpr([NotNull] JSONParser.SpellingExprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
