//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\bilsa\AppData\Roaming\RapidEditor\Extensions\Rapid_Extensions_Antlr\code_gen\201801\14\04\22\33_956\JSON.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JSONParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IJSONListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] JSONParser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] JSONParser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.topDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopDeclarations([NotNull] JSONParser.TopDeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.topDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopDeclarations([NotNull] JSONParser.TopDeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.topDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopDeclaration([NotNull] JSONParser.TopDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.topDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopDeclaration([NotNull] JSONParser.TopDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleDeclaration([NotNull] JSONParser.RuleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleDeclaration([NotNull] JSONParser.RuleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleDef([NotNull] JSONParser.RuleDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleDef([NotNull] JSONParser.RuleDefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleExpressions([NotNull] JSONParser.RuleExpressionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleExpressions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleExpressions([NotNull] JSONParser.RuleExpressionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.ruleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRuleExpr([NotNull] JSONParser.RuleExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.ruleExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRuleExpr([NotNull] JSONParser.RuleExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.regexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegexExpr([NotNull] JSONParser.RegexExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.regexExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegexExpr([NotNull] JSONParser.RegexExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.refExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefExpr([NotNull] JSONParser.RefExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.refExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefExpr([NotNull] JSONParser.RefExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSONParser.spellingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpellingExpr([NotNull] JSONParser.SpellingExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSONParser.spellingExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpellingExpr([NotNull] JSONParser.SpellingExprContext context);
}
