//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\bilsa\AppData\Roaming\RapidEditor\Extensions\Rapid_Extensions_Antlr\code_gen\201802\18\05\06\27_863\RSHARPParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="RSHARPParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IRSHARPParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] RSHARPParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] RSHARPParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.topStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopStatements([NotNull] RSHARPParser.TopStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.topStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopStatements([NotNull] RSHARPParser.TopStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopStatement([NotNull] RSHARPParser.TopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.topStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopStatement([NotNull] RSHARPParser.TopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceDeclaration([NotNull] RSHARPParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceDeclaration([NotNull] RSHARPParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceBody([NotNull] RSHARPParser.NamespaceBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceBody([NotNull] RSHARPParser.NamespaceBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclaration([NotNull] RSHARPParser.TypeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclaration([NotNull] RSHARPParser.TypeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclModifier([NotNull] RSHARPParser.TypeDeclModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclModifier([NotNull] RSHARPParser.TypeDeclModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclType([NotNull] RSHARPParser.TypeDeclTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclType([NotNull] RSHARPParser.TypeDeclTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclArgs([NotNull] RSHARPParser.TypeDeclArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclArgs([NotNull] RSHARPParser.TypeDeclArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclBody([NotNull] RSHARPParser.TypeDeclBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclBody([NotNull] RSHARPParser.TypeDeclBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclBodyStatements([NotNull] RSHARPParser.TypeDeclBodyStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclBodyStatements([NotNull] RSHARPParser.TypeDeclBodyStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclBodyStatement([NotNull] RSHARPParser.TypeDeclBodyStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclBodyStatement([NotNull] RSHARPParser.TypeDeclBodyStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaration([NotNull] RSHARPParser.MemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaration([NotNull] RSHARPParser.MemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberArgsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberArgsDecl([NotNull] RSHARPParser.MemberArgsDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberArgsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberArgsDecl([NotNull] RSHARPParser.MemberArgsDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberReturn([NotNull] RSHARPParser.MemberReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberReturn([NotNull] RSHARPParser.MemberReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclBody([NotNull] RSHARPParser.MemberDeclBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberDeclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclBody([NotNull] RSHARPParser.MemberDeclBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberModifier([NotNull] RSHARPParser.MemberModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberModifier([NotNull] RSHARPParser.MemberModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlock([NotNull] RSHARPParser.CodeBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.codeBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlock([NotNull] RSHARPParser.CodeBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.codeBlockOrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBlockOrValue([NotNull] RSHARPParser.CodeBlockOrValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.codeBlockOrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBlockOrValue([NotNull] RSHARPParser.CodeBlockOrValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.blockStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatements([NotNull] RSHARPParser.BlockStatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.blockStatements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatements([NotNull] RSHARPParser.BlockStatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.inlineExprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineExprStatement([NotNull] RSHARPParser.InlineExprStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.inlineExprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineExprStatement([NotNull] RSHARPParser.InlineExprStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStatement([NotNull] RSHARPParser.BlockStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.blockStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStatement([NotNull] RSHARPParser.BlockStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] RSHARPParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] RSHARPParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statementMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementMemberDeclaration([NotNull] RSHARPParser.StatementMemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statementMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementMemberDeclaration([NotNull] RSHARPParser.StatementMemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] RSHARPParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] RSHARPParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.ifThenElseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfThenElseStatement([NotNull] RSHARPParser.IfThenElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.ifThenElseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfThenElseStatement([NotNull] RSHARPParser.IfThenElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.thenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThenStatement([NotNull] RSHARPParser.ThenStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.thenStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThenStatement([NotNull] RSHARPParser.ThenStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] RSHARPParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] RSHARPParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] RSHARPParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] RSHARPParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] RSHARPParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] RSHARPParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachStatement([NotNull] RSHARPParser.ForEachStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.forEachStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachStatement([NotNull] RSHARPParser.ForEachStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprStatement([NotNull] RSHARPParser.ExprStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.exprStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprStatement([NotNull] RSHARPParser.ExprStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statementExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementExpr([NotNull] RSHARPParser.StatementExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statementExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementExpr([NotNull] RSHARPParser.StatementExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] RSHARPParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] RSHARPParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.leafExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeafExpr([NotNull] RSHARPParser.LeafExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.leafExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeafExpr([NotNull] RSHARPParser.LeafExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.groupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroupExpr([NotNull] RSHARPParser.GroupExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.groupExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroupExpr([NotNull] RSHARPParser.GroupExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.conditionOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionOp([NotNull] RSHARPParser.ConditionOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.conditionOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionOp([NotNull] RSHARPParser.ConditionOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.literalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExpr([NotNull] RSHARPParser.LiteralExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.literalExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExpr([NotNull] RSHARPParser.LiteralExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.refExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefExpr([NotNull] RSHARPParser.RefExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.refExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefExpr([NotNull] RSHARPParser.RefExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpr([NotNull] RSHARPParser.AssignmentExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpr([NotNull] RSHARPParser.AssignmentExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentLhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentLhs([NotNull] RSHARPParser.AssignmentLhsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentLhs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentLhs([NotNull] RSHARPParser.AssignmentLhsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOp([NotNull] RSHARPParser.AssignmentOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOp([NotNull] RSHARPParser.AssignmentOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.callArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArgs([NotNull] RSHARPParser.CallArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.callArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArgs([NotNull] RSHARPParser.CallArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.callArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArg([NotNull] RSHARPParser.CallArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.callArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArg([NotNull] RSHARPParser.CallArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgsDecl([NotNull] RSHARPParser.ArgsDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argsDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgsDecl([NotNull] RSHARPParser.ArgsDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgDecl([NotNull] RSHARPParser.ArgDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgDecl([NotNull] RSHARPParser.ArgDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeRef([NotNull] RSHARPParser.TypeRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeRef([NotNull] RSHARPParser.TypeRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceName([NotNull] RSHARPParser.NamespaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceName([NotNull] RSHARPParser.NamespaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeName([NotNull] RSHARPParser.TypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeName([NotNull] RSHARPParser.TypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceOrTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceOrTypeName([NotNull] RSHARPParser.NamespaceOrTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceOrTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceOrTypeName([NotNull] RSHARPParser.NamespaceOrTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDeclName([NotNull] RSHARPParser.TypeDeclNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDeclName([NotNull] RSHARPParser.TypeDeclNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberName([NotNull] RSHARPParser.MemberNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberName([NotNull] RSHARPParser.MemberNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgName([NotNull] RSHARPParser.ArgNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgName([NotNull] RSHARPParser.ArgNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] RSHARPParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] RSHARPParser.LiteralContext context);
}
