//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\bilsa\AppData\Roaming\RapidEditor\Extensions\Rapid_Extensions_Antlr\code_gen\201802\18\05\06\27_863\RSHARPParser.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IRSHARPParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class RSHARPParserBaseListener : IRSHARPParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocument([NotNull] RSHARPParser.DocumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.document"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocument([NotNull] RSHARPParser.DocumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.topStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopStatements([NotNull] RSHARPParser.TopStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.topStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopStatements([NotNull] RSHARPParser.TopStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.topStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTopStatement([NotNull] RSHARPParser.TopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.topStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTopStatement([NotNull] RSHARPParser.TopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] RSHARPParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] RSHARPParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceBody([NotNull] RSHARPParser.NamespaceBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceBody([NotNull] RSHARPParser.NamespaceBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclaration([NotNull] RSHARPParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclaration([NotNull] RSHARPParser.TypeDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclModifier([NotNull] RSHARPParser.TypeDeclModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclModifier([NotNull] RSHARPParser.TypeDeclModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclType([NotNull] RSHARPParser.TypeDeclTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclType([NotNull] RSHARPParser.TypeDeclTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclArgs([NotNull] RSHARPParser.TypeDeclArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclArgs([NotNull] RSHARPParser.TypeDeclArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclBody([NotNull] RSHARPParser.TypeDeclBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclBody([NotNull] RSHARPParser.TypeDeclBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclBodyStatements([NotNull] RSHARPParser.TypeDeclBodyStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclBodyStatements([NotNull] RSHARPParser.TypeDeclBodyStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclBodyStatement([NotNull] RSHARPParser.TypeDeclBodyStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclBodyStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclBodyStatement([NotNull] RSHARPParser.TypeDeclBodyStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclaration([NotNull] RSHARPParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclaration([NotNull] RSHARPParser.MemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberArgsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberArgsDecl([NotNull] RSHARPParser.MemberArgsDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberArgsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberArgsDecl([NotNull] RSHARPParser.MemberArgsDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberReturn([NotNull] RSHARPParser.MemberReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberReturn([NotNull] RSHARPParser.MemberReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberDeclBody([NotNull] RSHARPParser.MemberDeclBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberDeclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberDeclBody([NotNull] RSHARPParser.MemberDeclBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberModifier([NotNull] RSHARPParser.MemberModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberModifier([NotNull] RSHARPParser.MemberModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlock([NotNull] RSHARPParser.CodeBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.codeBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlock([NotNull] RSHARPParser.CodeBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.codeBlockOrValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBlockOrValue([NotNull] RSHARPParser.CodeBlockOrValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.codeBlockOrValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBlockOrValue([NotNull] RSHARPParser.CodeBlockOrValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.blockStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatements([NotNull] RSHARPParser.BlockStatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.blockStatements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatements([NotNull] RSHARPParser.BlockStatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.inlineExprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInlineExprStatement([NotNull] RSHARPParser.InlineExprStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.inlineExprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInlineExprStatement([NotNull] RSHARPParser.InlineExprStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockStatement([NotNull] RSHARPParser.BlockStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.blockStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockStatement([NotNull] RSHARPParser.BlockStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] RSHARPParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] RSHARPParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statementMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementMemberDeclaration([NotNull] RSHARPParser.StatementMemberDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statementMemberDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementMemberDeclaration([NotNull] RSHARPParser.StatementMemberDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] RSHARPParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] RSHARPParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.ifThenElseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfThenElseStatement([NotNull] RSHARPParser.IfThenElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.ifThenElseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfThenElseStatement([NotNull] RSHARPParser.IfThenElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.thenStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThenStatement([NotNull] RSHARPParser.ThenStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.thenStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThenStatement([NotNull] RSHARPParser.ThenStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] RSHARPParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] RSHARPParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] RSHARPParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] RSHARPParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] RSHARPParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] RSHARPParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.forEachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForEachStatement([NotNull] RSHARPParser.ForEachStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.forEachStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForEachStatement([NotNull] RSHARPParser.ForEachStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExprStatement([NotNull] RSHARPParser.ExprStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.exprStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExprStatement([NotNull] RSHARPParser.ExprStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.statementExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementExpr([NotNull] RSHARPParser.StatementExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.statementExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementExpr([NotNull] RSHARPParser.StatementExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] RSHARPParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] RSHARPParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.leafExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLeafExpr([NotNull] RSHARPParser.LeafExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.leafExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLeafExpr([NotNull] RSHARPParser.LeafExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.groupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroupExpr([NotNull] RSHARPParser.GroupExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.groupExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroupExpr([NotNull] RSHARPParser.GroupExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.conditionOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionOp([NotNull] RSHARPParser.ConditionOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.conditionOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionOp([NotNull] RSHARPParser.ConditionOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.literalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpr([NotNull] RSHARPParser.LiteralExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.literalExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpr([NotNull] RSHARPParser.LiteralExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.refExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRefExpr([NotNull] RSHARPParser.RefExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.refExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRefExpr([NotNull] RSHARPParser.RefExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpr([NotNull] RSHARPParser.AssignmentExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpr([NotNull] RSHARPParser.AssignmentExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentLhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentLhs([NotNull] RSHARPParser.AssignmentLhsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentLhs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentLhs([NotNull] RSHARPParser.AssignmentLhsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.assignmentOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentOp([NotNull] RSHARPParser.AssignmentOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.assignmentOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentOp([NotNull] RSHARPParser.AssignmentOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.callArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallArgs([NotNull] RSHARPParser.CallArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.callArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallArgs([NotNull] RSHARPParser.CallArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.callArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallArg([NotNull] RSHARPParser.CallArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.callArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallArg([NotNull] RSHARPParser.CallArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgsDecl([NotNull] RSHARPParser.ArgsDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argsDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgsDecl([NotNull] RSHARPParser.ArgsDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgDecl([NotNull] RSHARPParser.ArgDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgDecl([NotNull] RSHARPParser.ArgDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeRef([NotNull] RSHARPParser.TypeRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeRef([NotNull] RSHARPParser.TypeRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceName([NotNull] RSHARPParser.NamespaceNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceName([NotNull] RSHARPParser.NamespaceNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeName([NotNull] RSHARPParser.TypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeName([NotNull] RSHARPParser.TypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.namespaceOrTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceOrTypeName([NotNull] RSHARPParser.NamespaceOrTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.namespaceOrTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceOrTypeName([NotNull] RSHARPParser.NamespaceOrTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.typeDeclName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDeclName([NotNull] RSHARPParser.TypeDeclNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.typeDeclName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDeclName([NotNull] RSHARPParser.TypeDeclNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberName([NotNull] RSHARPParser.MemberNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.memberName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberName([NotNull] RSHARPParser.MemberNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.argName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgName([NotNull] RSHARPParser.ArgNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.argName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgName([NotNull] RSHARPParser.ArgNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="RSHARPParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] RSHARPParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="RSHARPParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] RSHARPParser.LiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
